name: append_new_account Run Newman Every 10 Minutes

on:
  schedule:
    - cron: '0 * * * *'  # Every hour, on the hour
  workflow_dispatch:        # Allow manual trigger

jobs:
  run-newman:
    runs-on: self-hosted  # Use your local runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install schedule

      - name: Run Python Newman Script
        run: 
            python C:\Users\jimmy\actions-runner\_work\API\API\append_new_account.py
            cd C:\Users\jimmy\Downloads\python_script
        env:
          PRD: https://trade.ytjokbt.com/v2
          PRD_MTRADE: https://39.108.127.136:6007/v1
