name: Run Newman Row by Row

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:     # Allow manual run

jobs:
  run-newman-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install schedule

    - name: Install Newman
      run: |
        npm install -g newman

    - name: Run Newman Python Script
      run: |
        python newman_runner.py
